### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by fsiddi** [oenvoyage/brender#1]
Maybe this is MAMP related, but I thought of giving this ticket system a try:)
if I start brender_server.php i get this:

<pre>
connect.php info :: ---- localhost,brender,brender ----
Warning: mysql_connect(): [2002] No such file or directory (trying to connect via unix:///var/mysql/mysql.sock) in /Applications/MAMP/htdocs/brender/connect.php on line 8

Warning: mysql_connect(): No such file or directory in /Applications/MAMP/htdocs/brender/connect.php on line 8
Fatal error: unable to connect to mysql server 
</pre>

**Comment by oenvoyage** [comment]
are you sure you set the DocumentRoot to the root of brender , and not brender/web ?

**Comment by fsiddi** [comment]
I needed to assign "Any host" with the % symbol (instead of "localhost") as a domain for the brender user in the database admin backend (Privileges section).

Now it works.
