### ISSUE TITLE
Server : Thumbnails

### ISSUE THREAD

**Issue by sebchardon** [oenvoyage/brender#12]
Hello,

I found a problem with displaying thumbnails, when I use Brender under a subdirectory or an Apache Alias.

Thumbnails are viewed with an absolute path : /thumbnails/<project>/....../...png ; wich works fine with a brender installation in root directory of Apache.

I made two little corrections, and it's work fine now for me (show git diff at the end).

Thanks a lot for your brender project !!

Sebastien

---

git diff :

<pre>
diff --git a/functions.php b/functions.php
index 9776f7d..72fcff2 100755
--- a/functions.php
+++ b/functions.php
@@ -679,6 +679,7 @@ function check_create_path($path) {
        #print "DEBUG --- $path chmod\n";
        $paths_array=explode("/",$path);
-        $current_path="";
+       $path_to_check="";
        #print_r($paths_array);
        foreach ($paths_array as $item) {
                #print "--- i am trying $item\n";
@@ -742,7 +743,7 @@ function get_thumbnail_image($job_id,$image_number,$class="") {
        $thumbnail_location="thumbnails/$project/$scene/$shot/small_$filename".str_pad($image_number,4,0,STR_PAD_LEFT).".$filetype";
        #print "**** $thumbnail_location****";
        if (file_exists("../$thumbnail_location")) {
-               return "<img src=\"/$thumbnail_location\" class=\"$class\">";
+               return "<img src=\"../$thumbnail_location\" class=\"$class\">";
        }
        else {
                return false;
diff --git a/web/view_image.php b/web/view_image.php
index d1a2f4c..1510bab 100755
--- a/web/view_image.php
+++ b/web/view_image.php
@@ -33,7 +33,7 @@
         // $file_name=$shot.str_pad($frame,4,0,STR_PAD_LEFT).".$filetype";
         $file_name=$shot_basename.str_pad($frame,4,0,STR_PAD_LEFT).".png";  // test fix for non-PNG jobs thumbnail generation

-        $thumbnail_location="/thumbnails/$project/$scene/$shot/$file_name";
+        $thumbnail_location="../thumbnails/$project/$scene/$shot/$file_name";

         $query="select rendered_by,finished_time from rendered_frames where job_id='$job_id' and frame='$frame'";
         $results=mysql_query($query);
</pre>

**Comment by fsiddi** [comment]
Hello Sebastien!
Thank you very much for your help! I will check it out in the second half of next week and possibly commit it right away:)
If you happen to find other small bugs or have any improvements to propose, feel free to write us.
We are very happy that you are taking advantage of the brender-farm!

Francesco

**Comment by sebchardon** [comment]
Hello Francesco,

I find 2 other links whith absolute path :
- on overview page, path to the refresh image : /web/images/icons/reload.png => images/icons/reload.png
- on clients page, path to the remove image : /web/images/icons/close.png => images/icons/close.png

And, on the server terminal, I have this error at the end of a job :
PHP Notice:  Undefined variable: heure in /nas/share/blender/brender/brender_server.php on line 155
But I don't really search how to correct it ^^

Both are not critical, it's only for the display. ;-)

By the way, for now, your system works perfectly for me !!

For your information : I'm using 3 computers, only on Linux, with a CIFS share for the brender repository.

Sebastien

**Comment by sebchardon** [comment]
oups, sorry ... wrong button ;-)

**Comment by oenvoyage** [comment]
fixes (finally) in
https://github.com/oenvoyage/brender/commit/0b5e358783bb11de140627f866bbe009b013edd5
