### ISSUE TITLE
Warning: fclose() expects parameter 1 to be resource, boolean given [Those darn relative paths]

### ISSUE THREAD

**Issue by stephen304** [oenvoyage/brender#17]
I get about a thousand of these errors constantly. I'm fairly certain that this is an issue with a code and not the way I have it set up, but if I am doing something wrong, please tell me! (I haven't modified any of the code)

Warning: fclose() expects parameter 1 to be resource, boolean given in H:\wamp\w
ww\brender\functions.php on line 419

Call Stack:
    0.0012     398072   1. {main}() H:\wamp\www\brender\brender_server.php:0
    3.7533     717928   2. checking_alive_clients() H:\wamp\www\brender\brender_
server.php:61
    5.7620     721112   3. brender_log() H:\wamp\www\brender\functions.php:638
    5.9428     722040   4. fclose() H:\wamp\www\brender\functions.php:419

Idk what it is with my computer and relative paths, but replacing all the stuff in the logging parts with absolute paths to the log folder and log files solved the problem. I better look up windows and relative paths so I can sort this out.

P.S. This program looks beautiful when there are no errors! :D Soo readable!

**Comment by oenvoyage** [comment]
Hello Stephen,
thanks for the windows patch, i applied it..
i did not have any problems here running on windows... its old win 2000
though.
for the error with fclose() it might be that the client or php process
doesnt have permission, i usually run them as root (not secure i know).
maybe there is something in the code to fix this... or not write log when
there is permission problem.
thank you for your help again

On 29 December 2011 03:05, Stephen304 <
reply@reply.github.com

> wrote:
> 
> I get about a thousand of these errors constantly. I'm fairly certain that
> this is an issue with a code and not the way I have it set up, but if I am
> doing something wrong, please tell me! (I haven't modified any of the code)
> 
> Warning: fclose() expects parameter 1 to be resource, boolean given in
> H:\wamp\w
> ww\brender\functions.php on line 419
> 
> Call Stack:
>    0.0012     398072   1. {main}() H:\wamp\www\brender\brender_server.php:0
>    3.7533     717928   2. checking_alive_clients()
> H:\wamp\www\brender\brender_
> server.php:61
>    5.7620     721112   3. brender_log()
> H:\wamp\www\brender\functions.php:638
>    5.9428     722040   4. fclose() H:\wamp\www\brender\functions.php:419
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/oenvoyage/brender/issues/17

## 

---

olivier amrein
http://oenvoyage.wordpress.com
company website : http://www.rgbprod.com
travel photos : http://www.flickr.com/photos/oenvoyage/collections/

**Comment by stephen304** [comment]
Well I am running the client in a command prompt that is started as administrator. Again, absolute paths solved the problem. I was up late last night so I didn't have time to finish looking into this. I'll try some more things and get back with a solution.

**Comment by stephen304** [comment]
It was the same backslash issue. I attempted a fix, though I'm a little less confident about this one since that code is supposed to run on all machines so I added in a variable ($slash) and some conditionals to alter slash in the case that the system is not the web interface and is not ajax AND the os is windows to that it is backslash instead. It seems to work.

**Comment by stephen304** [comment]
I have the same problem with the server. I assumed that it would be fixed, but $GLOBALS['os'] doesn't seem to be set on the server. I changed the log code to:

``` $foo=fopen($prefix."logs".$slash.$GLOBALS['os'].".log","a");
    fwrite($foo,"$log_koi");
    fclose($foo);
```

Lines 418, 419, 420 and I get this error in the console:

> Warning: fopen(logs.log): failed to open stream: No such file or directory in H:\wamp\www\brender\functions.php on line 418

"logs.log" suggests that the global os variable isn't set. I will continue to look into this issue. OS seems to be set on the client, as it is the basis for the windows backslash fix that I patched in the last pull.

**Comment by oenvoyage** [comment]
I made a commit rcently and added GLOBAL['os']: i hope it fixes, I can not test under windows for a few days.

**Comment by stephen304** [comment]
-snip- my copy was a tad out of date.

**Comment by oenvoyage** [comment]
normally i added get_server_settings("server_os") at start of brender_server...

**Comment by stephen304** [comment]
There we go. I also had to initialize the variable before functions.php was called to avoid other errors. Now I have absolutely 0 errors on startup.
