### ISSUE TITLE
On: view_job, tooltip gets cut off

### ISSUE THREAD

**Issue by stephen304** [oenvoyage/brender#23]
On the view_job page, the tooltip that pops up when the mouse is hovering over the job name (underneath job # <scene>/<shot>) that links back to the project page and reads "go to project page" gets cut off by an invisible element on the left side. Purely aesthetic and low priority.

**Comment by stephen304** [comment]
Of course a possible solution would be to nudge it over to the right a bit. I'm not sure how you intended it to look and I still don't know why it is being cut off. (Chrome & Firefox)

**Comment by oenvoyage** [comment]
i wished it was over all the page... I will ask my css guy if there is something to do ... 
if

**Comment by oenvoyage** [comment]
was fixed in https://github.com/oenvoyage/brender/commit/f1fb1525190a454d7722fa2136748234d56e1e3a
