### ISSUE TITLE
[Bug] Thumbnails fail to render until server restarts

### ISSUE THREAD

**Issue by stephen304** [oenvoyage/brender#26]
For some some reason, the thumbnails will fail to render (even when rendered locally by the server itself!) until the server is restarted and I manually reset the thumbnails to unrendered in mysql.

Also, I would like you to check the "windowsify_paths" function. I attempted to fix it, but I am unsure if I did it right.

**Comment by stephen304** [comment]
Bug found: Line 848 & 849 -> Uncomment

It seems like you commented them out because you were using a recursive mkdir? It doesn't seem to be recursive to me, or to the server. Would uncommenting them break it for you?

2012/01/01 17:27:14 : info : thumbnails/test_project/scene1/shot1 already exists
But it obviously doesn't...

**Comment by fsiddi** [comment]
This thread is marked as solved. Can we close it?
