### ISSUE TITLE
update jquery and jqueryui

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#28]
Could we update jquery to 1.7.1 and jqueryui to 1.8.16?
Also use the new .on() events of 1.7?

Jqueryui is just used here for buttons or? Why not then twitter bootstrap (just css)

**Comment by fsiddi** [comment]
Hello!
Thanks for your suggestions. I upgraded to 1.7.1 and everything seems to work fine. I also upgraded to 1.8.16.
I did not change anything related to on() events. Feel free to do it and submit the changes:)

We use jQueryUI also to run AJAX operations in the interface. I checked out bootstrap and it seems to be really cool, but I think it's not suitable for brender.

**Comment by DanielRuf** [comment]
Well thanks. I think I will change the events to '.on()' as they are faster and the other ones are deprecated as far as I know

Twitter bootstrap is mostly a css framework with some neat javascript plugins. Was just a suggestion =)

**Comment by DanielRuf** [comment]
Currently investigating the generated content (also repacing tablesorter with datatables as it is more w3c conform with theader and tbody ...) but need some error logs and where tables are generated / used which use tablesorter currently.

Also the datatables plugin has also paging and sorting already so there is no need anymore in the future for the order_by function so there are less database queries and also less requests
