### ISSUE TITLE
server as client

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#29]
Do you know if we can use a (cuda based) server as client with a server os (linux?)

**Comment by oenvoyage** [comment]
Hello 
I am not sure to understand your request. You can use any OS as a server, or client. 
If you refer to cuda for cycles rendering engine, Then the answer is yes, cycles gpu rendering works fine. 
If your question was about using any cuda technology to accelerate the server... then I don't know... (not sure it is necessary, as server only dispatches, which is not too ressource intensive i guess) 
If you have a server which is based on cuda, as long as it has a linux, php mysql, it should work fine.
I hope it answers your question :-)

**Comment by DanielRuf** [comment]
Thanks so I have to test this or ask an Nvidia employe.
