### ISSUE TITLE
mobile version / ui?

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#31]
We could use jquery mobile or twitter bootstrap for the mobile version
And also use a script to detect mobile devices and redirect to the mobile version directly

See also http://detectmobilebrowsers.com and http://stackoverflow.com/questions/3514784/best-way-to-detect-handheld-device-in-jquery

**Comment by fsiddi** [comment]
I created a fork for the development of a mobile UI (using the jQuery mobile framework). https://github.com/fsiddi/brender
Unfortunately I never managed to merge it due my inability to fix git issues. If you have time check it out!

**Comment by DanielRuf** [comment]
I think it doesnt need a full fork. A mobile detection script, an additional directory for mobile them / skin including all files and the remaining files and functions are the same. Doesnt seem to be so difficult. 

Is there an online demo of the mobile version?

**Comment by fsiddi** [comment]
There is no demo online atm, but https://github.com/fsiddi/brender is working as far as I recall. I think we should first talk about your roadmap proposal in general first.
