### ISSUE TITLE
render preview for video?

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#32]
I saw in the brender 0.5 video that there are frames / previews of the rendered blend files. Is this just for the shown  jpeg render mode or also for videos (with sound?)

So can I use the video render mode ? Where do I set the render settings?

**Comment by oenvoyage** [comment]
Hello Daniel,
no this is just a jpg preview of the files. We usually render as image sequences and then finalize with audio, so there is no movie preview, but you can use DJV or any sequence player to test the animation. 
You can not directly render to videos using brender, you render image sequences. That is because brender does dispatch frames to different machines. Usually making a movie out of frame sequences is a very easy and fast process.

**Comment by DanielRuf** [comment]
hm why not implement something like http://jsmovie.burkhardt-medienproduktion.de/ and https://github.com/benbyford/stopmotion-lite.js

also great is https://github.com/vkiryukhin/Smartupdater  

I would recommend these scripts

**Comment by stephen304** [comment]
I was looking into this earlier. My friend jury rigged a solution with ffmpeg, though that used platform specific code. I think ImageMagick might be able to construct an AVI. I've seen code that takes an image sequence and (supposedly) outputs an AVI, though I haven't tested this and I can't find any documentation on outputting videos with ImageMagick.

**Comment by DanielRuf** [comment]
Well this is no good solution as imagemagick might slow down the server and there is also no functional solution for this. Creating an avi should be done after the rendering but with a normal video programm and not serverside.

Jsmovie is currently the best solution (but modified and extensed with ajax and maybe json)

If we would like to use ffmpeg then we shoul serve a custom xampp build with it because installing and configuring fmpeg for webserver is not as easy as you think.

**Comment by oenvoyage** [comment]
Another solution is to setup a blend file that makes a movie file using the video sequence editor. Put it super low priority so it runs at the very end. It will compile your previeously rendered frames.  The only drawback is that it all outputs some frames. I will soon add an option to force the use of blender default output.
Furthermore I'm about to implement one of the Javascript for movie preview in the web interface. The stop.motion one did give good results.

**Comment by DanielRuf** [comment]
Hm well but jsmovie has some more features like pause stop forward backward ...  why not this one? It can be easiky changed to have the same performance as stopmotion lite

Or do you think we dont need these features for preview or we could them to stopmotion lite? I find jsmovie much better and flexible. I also developed in the past some addons for it and changed some code to work like stopmotion lite

I would like to improve jsmovie again and add some more features. Also jsmovie has an optional preloader like stopmotion lite but is much better to customize and developing. Will fork jsmovie again and add some features you want (showing current time of movie, frame x of y frames ... ?) Just tell me what you need and I will add this to jsmovie

What is currently with the json obj issue where I posted a solution? Does it work?

**Comment by oenvoyage** [comment]
I just commit a preview anim commit, based on stopmotion lite... as i started implementing before seeing your post...
if i get time i can reimplement with jsmovie... but dont know when... for now i like the stopmotion solution, its enough i think :)

**Comment by DanielRuf** [comment]
That would be great if you could do that sometime in the future with jsmovie =)

Well I could also help you with jsmovie (you just need to set it up and activate the preloader then it works like stopmotion lite).
