### ISSUE TITLE
jquery 1.7.1 issue fixed?

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#34]
https://github.com/oenvoyage/brender/commit/45e912a8b80d56326a95b8a65f281d6496092ccf

does this work now (with the 1.7.1 test version)?

**Comment by oenvoyage** [comment]
yes i finally had some time tonight to check your solution and as it worked ony my installation , i commited. :
https://github.com/oenvoyage/brender/commit/052b1c3a7ad41da39371e1b1032568af12d6acb2
thanks for your help

**Comment by DanielRuf** [comment]
now the next part is the one with datatables? 
has some great features the api of datatables (fixed columns, column reodering, json source, ajax, fixed header, column hiding, sorting, search, paging ...)

if you need help just let me know =)

**Comment by oenvoyage** [comment]
If You could point out a good beginners tutorial, I could give it a look :)
On Jan 28, 2012 5:38 PM, "Daniel Ruf" <
reply@reply.github.com>
wrote:

**Comment by DanielRuf** [comment]
Well I do not actually know specific tutorials but on api.jquery.com there are for each function some examples.

Tutsplus is a great ressource. I found there for example http://net.tutsplus.com/articles/web-roundups/jquery-for-absolute-beginners-video-series/

But I will help too as I work with jquery for some years now
