### ISSUE TITLE
port to sqlite 3

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#35]
We could port it to sqlite 3 so we do not need the phpmyadmin part.
Instead we could use http://code.google.com/p/phpliteadmin/

Goal is making a more portable server. Just copy later the whole dir with sqlite db file and clone the server making is easier to scale the serverfarm.

Also as the latest PHP release includes a built in server we do not need apache (maybe) and also save this.
What do you think?

**Comment by fsiddi** [comment]
Hey!
Your points look interesting, but I think it's a pretty ambitious plan:) 
At the moment both me and oenvoyage are quite busy so we don't have much time to keep track of this. If you think you could do it yourself we can figure out a solution to implement it (maybe offering it as an alternative to mysql in the setup). Let me know, thanks!

**Comment by DanielRuf** [comment]
Well I will work on the sqlite version soon and commit the additional sources. Sure, we should keep an option to select between MySQL and SQLite (while SQLite makes it more portable and easier to setup maybe)

But I think I will do this with the recoding of brender with the Zend Framework (MVC) as it makes ist more clear and easier to customize and much faster while you part the data and structure.

**Comment by fsiddi** [comment]
Will recoding brender with the Zend Framework have a massive impact on the code? Could you please share some more infos about this? I'm very excited about this!
Have you evaluated other frameworks such as CakePHP for instance?

**Comment by DanielRuf** [comment]
I worked already with Zend Framework and it is the best solution I used until now.

**Comment by fsiddi** [comment]
Great! check out my reply on issue #33 !
