### ISSUE TITLE
integrate datatables plugin

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#36]
For the tables we can use the great datatables plugin.

The structure of the tables should have the right structure (thead, tbody ...)

It has some nice plugins like scrollable inner tables, fixed columns, fixed header ...

I could need a database dump with example data for testing as I have not so much time this weekend but I want to integrate the datatables plugin soon

**Comment by oenvoyage** [comment]
I had a quick look at datatable and i think it is a good olution, it could help a lot with big lists of jobs or clients... 
It would be good if you could do some tests. 
Imho it is more usefull than changing the database to sqlite. And maybe as its smaller project, could help you to dig and understand a bit the codebase.
I will also have a look someday :)

**Comment by DanielRuf** [comment]
Well then I could need a database (mysql) with sample data for testing as I can not create some data for testing.

**Comment by oenvoyage** [comment]
What is wrong or not working ?

On 12 February 2012 13:18, Daniel Ruf <
reply@reply.github.com

> wrote:
> 
> Well then I could need a database (mysql) with sample data for testing as
> I can not create some data for testing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/oenvoyage/brender/issues/36#issuecomment-3927439

## 

---

olivier amrein
http://oenvoyage.wordpress.com
company website : http://www.rgbprod.com
travel photos : http://www.flickr.com/photos/oenvoyage/collections/

**Comment by DanielRuf** [comment]
I have here no example data for testing and so I need just a simple mysql databse with some test data (enough data to test paging for tables and so on).
