### ISSUE TITLE
Zend Framework port

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#37]
17.2.2012:started porting to Zend Framework

**Comment by fsiddi** [comment]
Great news!
May I ask a couple of questions, like:
- where/when do you plan to commit the code?
- are you writing it from scratch?

F

**Comment by DanielRuf** [comment]
- dont know actually  - should not take to long
- yes - full mvc driven but porting existing functions

**Comment by fsiddi** [comment]
All right!
Let us know when you'll have any updates:)

**Comment by DanielRuf** [comment]
Well, currently we should focus first on new features and optimization and later do a recode as I think but I made some progress currently =)
