### ISSUE TITLE
Warning: mysql_connect(): [2002] No such file or directory

### ISSUE THREAD

**Issue by fsiddi** [oenvoyage/brender#38]
When launching `php brender_server.php` I get the following message:

```
connect.php info :: ---- localhost,brender,brender ----
Warning: mysql_connect(): [2002] No such file or directory (trying to connect via unix:///var/mysql/mysql.sock) in /Applications/MAMP/htdocs/brender-mobile/connect.php on line 8

Warning: mysql_connect(): No such file or directory in /Applications/MAMP/htdocs/brender-mobile/connect.php on line 8
```

It happend already in the past but I can't recall what it was due to.
Any tips?

**Comment by oenvoyage** [comment]
So it seems its better to put the full ip adress, instead of just localhost... also MAMP's default port is 8889... 
also we need to make sure the brender user in mysql has authorization for all hosts (%)
