### ISSUE TITLE
Chunk size limit

### ISSUE THREAD

**Issue by fsiddi** [oenvoyage/brender#49]
I noticed that the max chunk size for a job is 127. I was wondering what is the reasoning beyond this?

**Comment by oenvoyage** [comment]
There is no real reason, I made the sql field in the database a TINYINT,
which means it maxes out when inserting the row at 127 (don't know why it's
not 255 by the way).
You can change this by going in mysql and changing chunks field from
TINYINT to INT, can max out at moar
In which case would you render by chunks > 127?

It's no problem to change it by default, so we can do it. It's in the
brnder.swl in install/

On 18 September 2012 16:08, Francesco Siddi notifications@github.comwrote:

> I noticed that the max chunk size for a job is 127. I was wondering what
> is the reasoning beyond this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oenvoyage/brender/issues/49.

## 

---

olivier amrein
http://oenvoyage.wordpress.com
company website : http://www.rgbprod.com
travel photos : http://www.flickr.com/photos/oenvoyage/collections/

**Comment by MrPetru** [comment]
Sorry, but time ago was a situation where I had to render 10K frames on
five computers. Each frame was rendered in 3 second (few composing
changes). As brender have at maximum 127 chunk size for core, this took to
me 3 hours to complete entire job. For second try, I changed slaves
propriety from 2 core each to 24 core. With this new configuration I was
able to send 24*127 frames to each slave and at this time, render job was
finished in 15 min.
In my opinion, there can be few situations where is more efficiently where
chunk size is more flexible without need to found an extra solution. Or
maybe an multiplier which can scale chunk size like changing core number.
But if you have 50 slaves this would be very tedious job. Or if all you
computers have 24 core the this wouldn't be a problem :)
Il giorno 18/set/2012 17:40, "Olivier Amrein" notifications@github.com ha
scritto:

> There is no real reason, I made the sql field in the database a TINYINT,
> which means it maxes out when inserting the row at 127 (don't know why
> it's
> not 255 by the way).
> You can change this by going in mysql and changing chunks field from
> TINYINT to INT, can max out at moar
> In which case would you render by chunks > 127?
> 
> It's no problem to change it by default, so we can do it. It's in the
> brnder.swl in install/
>

**Comment by oenvoyage** [comment]
oh yes if per frame rendering time is very small, it's definitely a case.
I commited the changes to default install files... (https://github.com/oenvoyage/brender/commit/2c085fc4f70c93f79a1423cb0beefcc9457f72c7) 
fresh installs will not have this limit. 
for existing installs it is worth to change the chunk field to int(11). 
we can now have a max chunk of 2147483647
