### ISSUE TITLE
Cameras

### ISSUE THREAD

**Issue by gl1ch** [oenvoyage/brender#52]
Please forgive me if this is a stupid question but I dont use Blender on a day to day basis. We are currently testing Brender and our 3D guy was wondering how he would go about selecting which camera the video or still would render from?

**Comment by oenvoyage** [comment]
Hello
Thanks for trying out Brender 0.5 
There is no fast way to select camera from the brender interface...you could always add a line in the python configuration file.
Also please note that there is a newer version of brender in developement at https://github.com/fsiddi/brender
