### ISSUE TITLE
view_job page breaks layout

### ISSUE THREAD

**Issue by fsiddi** [oenvoyage/brender#6]
A badly formatted table is being created. This breaks the layout and causes the footer not to stitch anymore to the bottom of the page. 
fsiddi looks into this.

**Comment by oenvoyage** [comment]
do you still have this problem ? i dont see any problem with my footers

**Comment by fsiddi** [comment]
I still do, and I don't see the thumbanils (I checked and the seem to be created and placed in the correct folder). Could you send me a screenshot of what you see?

**Comment by fsiddi** [comment]
I am starting to understand the issue. If you load the page like this

<pre>index.php?view=view_job&id=144</pre>

it is going to show the broken layout (and just one thumbnail). If you write

<pre>index.php?view=view_job&id=144&visual=1</pre>

everything is ok. The first link gets created in the jobs page, while clicking on the job name. If you click on the image preview you get the second one.

**Comment by oenvoyage** [comment]
corrected now. closing it.
