### ISSUE TITLE
Working hours

### ISSUE THREAD

**Issue by fsiddi** [oenvoyage/brender#7]
When I start the server i get this error:

<pre>
Warning: mysql_fetch_object(): supplied argument is not a valid MySQL result resource in /Applications/MAMP/htdocs/brender/brender_server.php on line 129
</pre>

Is it an issue or my database is not updated at the latest version?

**Comment by oenvoyage** [comment]
you need to add the rendered_frames table. check the mysql dump
andmaybe it needs to have at least one item.
if this is the case, we can add one in the mysql dump of installation script.

**Comment by fsiddi** [comment]
Ok, this is fixed, and I will update the installer also.
